### ISSUE TITLE
Work only in symfony 2.7 ?

### ISSUE THREAD

**Issue by gponty** [yectep/phpspreadsheet-bundle#1]
![selection_055](https://user-images.githubusercontent.com/34276317/36590636-950411a0-188f-11e8-941a-a4fc33602209.png)

thank you !

**Comment by eightyknots** [comment]
I tagged the current master which includes support for symfony ~2.7|~3.0|~4.0. A simple `composer update yectep/phpspreadsheet-bundle` should suffice.

This should let you install on 3.3 now 😄
