### ISSUE TITLE
Symfony 5 autowiring error

### ISSUE THREAD

**Issue by goodjinny** [yectep/phpspreadsheet-bundle#19]
Hi, @yectep!

After moving project to Symfony 5, have got an error:

`    Cannot autowire service "path\to\project\service\class": argument "$spreadsheetFactory" of method "__construct()" references class "Yectep\PhpSpreadsheetBundle\Factory" but no such service exists. You should maybe alias this class to the existing "phpoffice.spreadsheet" service.`

It could be fixed by declearing an alias for **phpofficebundle_spreadsheet_class**. I've created a pull request https://github.com/yectep/phpspreadsheet-bundle/pull/18 with related fix. Can you review it?

**Comment by eightyknots** [comment]
Reviewed, merged, and published as v0.1.1.

Thanks for contributing!
