### ISSUE TITLE
Attempted to load class "Factory"

### ISSUE THREAD

**Issue by andrea-daru** [yectep/phpspreadsheet-bundle#2]
> Attempted to load class "Factory" from namespace "Yectep\PhpSpreadsheetBundle".
Did you forget a "use" statement for e.g. "Symfony\Component\Lock\Factory" ?

I'm on Symfony 3.4.6.
Someone has the same problem? Solutions?

**Comment by smbpunt** [comment]
Same problem on Symfony 2.7

**Comment by hunslater** [comment]
Move the "Factory" to the src dir

**Comment by andrea-daru** [comment]
@yectep can you ad me as contributor? I'll change the location of Factory class.
thx

**Comment by eightyknots** [comment]
@andrea-daru I added you as collab, or feel free to submit a PR and I can merge it too. Thanks!

**Comment by andrea-daru** [comment]
@yectep Change made and pushed/merged in the master.
It's possible to release a version to include the change in composer?
thx

**Comment by eightyknots** [comment]
I've pushed tag v0.0.3 to this repo, packagist.org should be updated momentarily.

https://github.com/yectep/phpspreadsheet-bundle/releases/tag/v0.0.3
