### ISSUE TITLE
Notice: Undefined index: $

### ISSUE THREAD

**Issue by SergioVasko** [yectep/phpspreadsheet-bundle#21]
Related to https://github.com/PHPOffice/PhpSpreadsheet/pull/1326
Needs update PhpSpreadsheet to 1.13.0

**Comment by fd6130** [comment]
Is this issue still persist?

**Comment by Chris53897** [comment]
According to https://github.com/eightyknots/phpspreadsheet-bundle/blob/master/composer.json yes.
@SergioVasko can you confirm and close this issue?
